name: Makefile CI

on:
  push:
    branches: [ "main", "link-lst" ]
  pull_request:
    branches: [ "main", "link-lst" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: make debug
      run: make debug
    - name: make benchmark
      run: bash benchmark.sh
