name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: make debug
      run: make debug
    - name: make benchmark
      run: make benchmark
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Changed files
